server:
  port: 9995

management:
  port: 9995
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      enabled: true
    metrics:
      enabled: true
    health:
      show-details: always
  info:
    env:
      enabled: true

spring:
  application:
    name: gateway-app
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: EUREKA-CLIENT-EXAMPLE
          uri: lb://EUREKA-CLIENT-EXAMPLE
          predicates:
            - Path=/eureka/**
          filters:
            - RewritePath=/eureka/(?<path>.*), /$\{path}
#        - id: FEIGN-EXAMPLE
#          uri: lb://FEIGN-EXAMPLE
#          predicates:
#            - Path=/feign/**
#          filters:
#            - RewritePath=/feign/(?<path>.*), /$\{path}
  security:
    user:
      name: admin
      password: admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
